spring:
  application:
    name: notifyme.desdelamesa.online
  data:
    redis:
      repositories:
        enabled: true
      database: 0
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      timeout: 5000
      connect-timeout: 5000
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notifyme}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      connection-timeout: 5000
      idle-timeout: 30000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  error:
    whitelabel:
      enabled: false
environment: PROD
api:
  key:
    value: ${X-API-KEY:1234567890}
